"""initial schema

Revision ID: a6e5333f99bf
Revises: 
Create Date: 2026-04-18 14:08:16.526490

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a6e5333f99bf'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('orgs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('aircraft_specs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('org_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('length_m', sa.Float(), nullable=False),
    sa.Column('wingspan_m', sa.Float(), nullable=False),
    sa.Column('tail_height_m', sa.Float(), nullable=False),
    sa.Column('fuselage_width_m', sa.Float(), nullable=False),
    sa.Column('wing_root_height_m', sa.Float(), nullable=False),
    sa.Column('wing_thickness_m', sa.Float(), nullable=False),
    sa.Column('wing_type', sa.Enum('high', 'low', name='wingtype'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['org_id'], ['orgs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('hangars',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('org_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('length_m', sa.Float(), nullable=False),
    sa.Column('width_m', sa.Float(), nullable=False),
    sa.Column('height_m', sa.Float(), nullable=False),
    sa.Column('roof_type', sa.Enum('flat', 'gabled', 'arched', name='rooftype'), nullable=False),
    sa.Column('roof_peak_height_m', sa.Float(), nullable=False),
    sa.Column('roof_eave_height_m', sa.Float(), nullable=False),
    sa.Column('buffer_m', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['org_id'], ['orgs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('org_id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('hashed_password', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['org_id'], ['orgs.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('layouts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('hangar_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['hangar_id'], ['hangars.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('placed_aircraft',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('layout_id', sa.Integer(), nullable=False),
    sa.Column('spec_id', sa.Integer(), nullable=False),
    sa.Column('x_m', sa.Float(), nullable=False),
    sa.Column('z_m', sa.Float(), nullable=False),
    sa.Column('rotation_rad', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['layout_id'], ['layouts.id'], ),
    sa.ForeignKeyConstraint(['spec_id'], ['aircraft_specs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('placed_aircraft')
    op.drop_table('layouts')
    op.drop_table('users')
    op.drop_table('hangars')
    op.drop_table('aircraft_specs')
    op.drop_table('orgs')
    # ### end Alembic commands ###
