"""add elevator_span_m to aircraft_specs

Revision ID: fd2b5b9032dc
Revises: a6e5333f99bf
Create Date: 2026-04-18 15:20:44.933569

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fd2b5b9032dc'
down_revision: Union[str, Sequence[str], None] = 'a6e5333f99bf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('aircraft_specs', sa.Column('elevator_span_m', sa.Float(), nullable=False, server_default='0'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('aircraft_specs', 'elevator_span_m')
    # ### end Alembic commands ###
